Feature add lock scale option
FIGS-FESS/FESSGUI pull request #39
Opened 2016-11-10 01:06 UTC by Zyrck56

Feature implemented and working to the best of my knowledge.
Changes also include a typo fix, a 33ms wait time instead of 30ms, and magic number removal.

2016-11-10 07:07 UTC, ghost reviewed
Code looks good other than my question about headers.

2016-11-10 07:07 UTC, bolt1003 commented on FESS-GUI/mainwindow.h
> +    bool isScaleLocked = false;
Do we want to initialize variables in the headers or do it in the constructor?

2016-11-10 17:04 UTC, JCJutson requested changes

2016-11-10 17:04 UTC, JCJutson commented on FESS-GUI/graph.cpp
> +    if(maxValue < 0){
Currently, it is possible that maxValue will have a negative value. We should look into fixing that. There are some weird consequences. I'll bring it up in the meeting

2016-11-10 17:04 UTC, JCJutson commented on FESS-GUI/mainwindow.h
> +    bool isScaleLocked = false;
Yeah, let's be consistent with how we do this

2016-11-10 17:04 UTC, JCJutson commented on FESS-GUI/mainwindow.cpp
> +        velocityGraph->addData(currentTime, actualVelocity, radsPerSecondToRPM(currentExpectedVelocity), ui->velocitySlider->maximum());
I think we discussed using the slider maximum + 5% for the graph maximum

2016-11-10 23:48 UTC, JCJutson approved these changes

2016-11-11 05:44 UTC, ghost requested changes

2016-11-11 05:44 UTC, bolt1003 commented on FESS-GUI/mainwindow.cpp
> +        graphRefreshRate = 33;
Refresh Rates are now saved as FPS/HZ. The original 30 would be correct. 1000/30 is done in a function to get the 33ms for the timer.

2016-11-11 06:18 UTC, Zyrck56 commented on FESS-GUI/mainwindow.cpp
> +        graphRefreshRate = 33;
okay. fixed

2016-11-11 08:26 UTC, ghost approved these changes

2016-11-11 08:27 UTC, merged